[build]
  publish = "."
  command = ""

# This section prevents Netlify from trying to run Jekyll
[build.environment]
  JEKYLL_ENV = "production"

# Ensures that refreshing the page doesn't result in a 404
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[primary]
  command = ""
